############################################################################
#
# Imperial College London, United Kingdom
# Multifunctional Nanomaterials Laboratory
#
# Project:  ERASE
# Year:     2021
# Python:   Python 3.7
# Authors:  Ashwin Kumar Rajagopalan (AK)
#
# Purpose:
# Clean the experimental .mat file generated by each ZLC run
#
# Last modified:
# - 2021-03-24, AK: Initial creation
#
# Input arguments:
#
#
# Output arguments:
#
#
############################################################################

import auxiliaryFunctions
import scipy.io as sio
import numpy as np
import os
from numpy import savez
import socket

# Get the commit ID of the current repository
gitCommitID = auxiliaryFunctions.getCommitID()

# Directory of raw data
mainDir = '/Users/ash23win/Google Drive/ERASE/experimental/runData/'
# File name of the experinent
fileName = 'ZLC_DeadVolume_Exp05A_Output.mat'
# Path of the file name
fileToLoad = mainDir + fileName

# Load .mat file
rawData = sio.loadmat(fileToLoad)["experimentOutput"]
# Convert the nDarray to list
nDArrayToList = np.ndarray.tolist(rawData)
# Unpack another time (due to the structure of loadmat)
tempListData = nDArrayToList[0][0]
# Get the necessary variables
timeElapsed = tempListData[0]
moleFrac = tempListData[1]
flowRate = tempListData[2]

# Save the array concentration into a native numpy file
# The .npz file is saved in a folder called simulationResults (hardcoded)
saveFileName = fileName[0:-4] + "_" + gitCommitID;
savePath = os.path.join('runData',saveFileName)
savez (savePath, timeElapsed = timeElapsed, # Time elapsed [s]
        moleFrac = moleFrac, # Mole fraction of CO2 [-]
        flowRate = flowRate, # Total flow rate [ccs]
        hostName = socket.gethostname()) # Hostname of the computer